# .github/workflows/deploy-to-snowflake.yml
name: CI/CD → Snowflake

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Generate YAML from SQL
        run: |
          python scripts/sql_to_yaml.py

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql
          chmod +x snowsql
          sudo mv snowsql /usr/local/bin/

      - name: Deploy to Snowflake
        env:
          SNOWSQL_ACCOUNT:    ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER:       ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PWD:        ${{ secrets.SNOWFLAKE_PWD }}
          SNOWSQL_ROLE:       ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWSQL_WAREHOUSE:  ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWSQL_DATABASE:   ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWSQL_SCHEMA:     ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          yq e '.[] .custom_TSQL' -o=plain *.yaml \
            | snowsql \
                -a $SNOWSQL_ACCOUNT \
                -u $SNOWSQL_USER \
                -p $SNOWSQL_PWD \
                -r $SNOWSQL_ROLE \
                -w $SNOWSQL_WAREHOUSE \
                -d $SNOWSQL_DATABASE \
                -s $SNOWSQL_SCHEMA \
                --echo-all

      - name: Success notification
        if: success()
        run: echo "🎉 Deployed to Snowflake successfully!"
