name: Snowflake CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Snowflake
        run: |
          snowsql -a ${{ secrets.SNOWFLAKE_ACCOUNT }} \
                  -u ${{ secrets.SNOWFLAKE_USER }} \
                  -p ${{ secrets.SNOWFLAKE_PASSWORD }} \
                  -d MY_DB -s public -r SYSADMIN \
                  -f cicd/deploy.sql
